---
- name: Deployment
  hosts: prodvm
  become: true
  become_user: root
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        force: true
      loop:
        - { src: "/home/runner/work/desofs2024_M1A_6/desofs2024_M1A_6/Code/BE", dest: "/usr/src/Code/BE/" }
        - { src: "/home/runner/work/desofs2024_M1A_6/desofs2024_M1A_6/Code/FE", dest: "/usr/src/Code/FE/" }
        
    - name: Execute commands
      command: /bin/sh -c "cd /usr/src/Code/Infrastructure/docker && docker-compose up --build fe be"
    # - name: Fix keycloak
    #   command: docker exec -it docker_keycloak_1 sh -c 'sleep 240 && cd /opt/keycloak/bin/ && ./kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password admin && ./kcadm.sh update realms/master -s sslRequired=NONE'"
