---
- name: Deployment
  hosts: prodvm
  become: yes
  become_user: root
  vars_files:
    - vars.yaml
  tasks:
    - name: Copy files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - { src: "/Code/BE", dest: "/usr/src/Code/BE/" }
        - { src: "/Code/FE", dest: "/usr/src/Code/FE/" }
        
    - name: Execute commands
      command: /bin/sh -c "cd /usr/src/Code/Infrastructure/docker && docker-compose up -d --build fe be && docker exec -it docker_keycloak_1 sh -c 'sleep 240 && cd /opt/keycloak/bin/ && ./kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password admin && ./kcadm.sh update realms/master -s sslRequired=NONE"
