version: '3'
services:
  fe:
    build:
      context: "../../FE"
      args:
        - PROJECT_PATH=./desofs-news
    ports:
      - "4200:4200"
    volumes:
      - ../../FE/desofs-news:/usr/src/app
    networks:
      my_network:
        ipv4_address: 172.25.0.2   # Assigning IP address to frontend
    depends_on:
      - be
  # Missing test connection
  be:
    build:
      context: "../../BE"
      args:
        - PROJECT_PATH=.
    volumes:
      - ../../BE:/usr/src/app
    networks:
      my_network:
        ipv4_address: 172.25.0.3   # Assigning IP address to backend
    expose:
      - 9090
    # depends_on:
    #   - db

  # Missing keycloak and database
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak_v1
      KC_DB_PASSWORD: root
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_JDBC_PARAMS: 'sslmode=require'
    ports:
      - "9090:8080"
    depends_on:
      - postgres
        # condition: service_healthy
    networks:
      my_network:
        ipv4_address: 172.25.0.4

  postgres:
    image: postgres:10
    command: ["postgres", "-c", "max_connections=200", "-c", "shared_buffers=24MB", "-c", "listen_addresses=*"]
    environment:
      POSTGRES_DB: keycloak_v1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: "exit 0"
    expose:
      - 5432
    networks:
      my_network:
        ipv4_address: 172.25.0.5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: postgres


volumes:
  postgres_data:

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16   # Define the subnet for your custom network
