name: Angular Pipeline

env:
  DOCKERFILE_PATH: ./Code/FE/Dockerfile
  DOCKER_IMAGE_NAME: frontend-image

# run on every push to all branches
on:
  push:
    branches:
      - main
      - feature/*
    paths: 
      - ./Code/FE/*
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: All Steps (Build, Test & Deploy)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"

      - name: get the working directory
        run: pwd

      - name: Install Dependencies
        run: cd ./Code/FE/desofs-news && npm install

      - name: Build
        run: cd ./Code/FE/desofs-news && npm run build

      - name: Test
        run: cd ./Code/FE/desofs-news && npm run test -- --watch=false --browsers=ChromeHeadless

  sonar:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_FE }}

  image_scan:
    name: Build and Run Image Scan
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '26.1.3'

    - name: Build Docker Image
      run: docker build -f ${{ env.DOCKERFILE_PATH }} -t ${{ env.DOCKER_IMAGE_NAME }}:latest .

    - name: Docker Scout Scan
      uses: docker/scout-action@v1.8.0
      with:
        dockerhub-user: ${{ secrets.DOCKER_USER }}
        dockerhub-password: ${{ secrets.DOCKER_PWD }}
        command: quickview,cves
        only-severities: critical,high
        sarif-file: angular-scout-report.sarif

    - name: Upload Artificat
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: docker-scout-findings
        path: angular-scout-report.sarif
        