name: deploy

on:
  - workflow_call

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      - name: Copy ansible directory to runner
        shell: bash
        run: |
          mkdir /home/runner/ansible
          cp -R ./Code/Infrastructure/ansible/* /home/runner/ansible
  
      - name: Run ansible script
        env:
          PEDRO_DO_API_KEY: ${{ secrets.PEDRO_DO_API_KEY }}
        run: |
          cd /home/runner/ansible
          ansible-playbook -i hosts playbook.yml
    # cd /home/runner/ansible
      