name: deploy

on:
  - workflow_call

jobs:
  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up SSH
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          service ssh status
          eval `ssh-agent -s`

          mkdir -p /home/runner/.ssh/
          echo "$SSH_KEY" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-keyscan github.com >> /home/runner/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install ansible

      - name: Copy ansible directory to runner
        shell: bash
        run: |
          mkdir /home/runner/ansible
          cp -R ./Code/Infrastructure/ansible/* /home/runner/ansible
          ssh -i /home/runner/.ssh/id_rsa root@206.189.24.67
  
      - name: Run ansible script
        shell: bash
        run: |
          cd /home/runner/ansible
          ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa -i hosts playbook.yml
      
      # - name: SSH into VM and rebuild docker images
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: 206.189.24.67
      #     username: root
      #     port: 22
      #     # password: rootadmin
      #     key: ${{ secrets.SSH_KEY }}
      #     # Only re-build fe, be
      #     script: |
      #       cd /usr/src/Code/Infrastructure/docker
      #       docker-compose up -d --build fe be
      #       docker exec -it docker_keycloak_1 sh -c 'sleep 240 && cd /opt/keycloak/bin/ && ./kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin --password admin && ./kcadm.sh update realms/master -s sslRequired=NONE'
