name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate FE dependencies file and zip
      run: |
        cd ./Code/FE/
        zip -r fe.zip desofs-news -x
        ls
        cp -R fe.zip ../../
        npm i
        npm ls --depth=0 | awk 'NR>1 {print $2}' > dependencies.txt
    
    - name: Generate BE dependencies file and zip
      run: |
        cd ./Code/
        zip -r be.zip BE -x
        cp -R be.zip ../
        mvn dependency:tree -DoutputType=text | grep -P '^\[INFO\] +- ' | sed 's/^\[INFO\] +- //' > dependencies.txt


    - name: Combine dependencies files
      run: |
        touch combined-dependencies.txt
        cd ./Code/FE/desofs-news
        echo "Angular dependencies:" >> ../../../combined-dependencies.txt
        echo " " >> ../../combined-dependencies.txt
        cat dependencies.txt > ../../../combined-dependencies.txt
        cd ../../../Code/BE
        echo "Java dependencies:" >> ../../combined-dependencies.txt
        echo " " >> ../../combined-dependencies.txt
        cat dependencies.txt >> ../../combined-dependencies.txt

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "fe.zip,be.zip"
        bodyFile: "combined-dependencies.txt"
        prerelease: true
        generateReleaseNotes: true