name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Generate FE dependencies file
      run: |
        cd ./Code/FE/desofs-news
        npm i
        npm ls --depth=0 | awk 'NR>1 {print $2}' > dependencies.txt
    
    - name: Generate BE dependencies file
      run: |
        cd ./Code/BE
        grep '<artifactId>.*</artifactId>' pom.xml | sed -e 's/<artifactId>//g' -e 's/<\/artifactId>//g' -e 's/\t//g' | tail -n +3 > dependencies.txt
    
    - name: Generate SBOMs
      run: |
        cd ./Code/FE/desofs-news && npm run generate-sbom
        mv sbom.json ../../../fe-sbom.json
        cd ../../../Code/BE/
        mvn -B clean install --file pom.xml
        mv target/bom.xml ../../be-bom.xml

    - name: Combine dependencies files and dependency files
      run: |
        zip -r package.zip ./Code/BE ./Code/FE/desofs-news

        touch combined-dependencies.txt
        echo "Angular dependencies:" >> combined-dependencies.txt
        echo " " >> combined-dependencies.txt
        cd ./Code/FE/desofs-news
        cat dependencies.txt >> ../../../combined-dependencies.txt
        cd ../../../Code/BE
        echo "Java dependencies:" >> ../../combined-dependencies.txt
        echo " " >> ../../combined-dependencies.txt
        cat dependencies.txt >> ../../combined-dependencies.txt


    - uses: ncipollo/release-action@v1
      with:
        artifacts: "package.zip,fe-sbom.json,be-bom.xml"
        bodyFile: "combined-dependencies.txt"
        prerelease: true
        generateReleaseNotes: true