name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: actions/upload-artifact@v4
      with:
        name: code
        path: ./Code

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "code.*"
        bodyFile: "README.md"