name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/upload-artifact@v4
      with:
        name: fe
        path: ./Code/FE/desofs-news
    - name: Generate Angular dependencies file
      run: |
        cd ./Code/FE/
        ls
        cp -R fe.zip ../../
        npm i
        npm ls --depth=0 | awk 'NR>1 {print $2}' > dependencies.txt
    
    - uses: actions/upload-artifact@v4
      with:
        name: be
        path: ./Code/BE
    - name: Generate Java dependencies file
      run: |
        cd ./Code/
        cp -R be.zip ../../
        mvn dependency:tree -DoutputType=text | grep -P '^\[INFO\] +- ' | sed 's/^\[INFO\] +- //' > dependencies.txt


    - name: Combine dependencies files
      run: |
        touch combined-dependencies.txt
        cd ./Code/FE/desofs-news
        echo "Angular dependencies:" >> ../../../combined-dependencies.txt
        echo " " >> ../../combined-dependencies.txt
        cat dependencies.txt > ../../../combined-dependencies.txt
        cd ../../../Code/BE
        echo "Java dependencies:" >> ../../combined-dependencies.txt
        echo " " >> ../../combined-dependencies.txt
        cat dependencies.txt >> ../../combined-dependencies.txt

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "fe.zip,be.zip"
        bodyFile: "combined-dependencies.txt"
        prerelease: true
        generateReleaseNotes: true