name: Release

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Generate FE dependencies file and zip
      run: |
        cd ./Code/FE/
        zip -r fe.zip desofs-news
        cp -R fe.zip ../../

        cd desofs-news
        npm i
        npm ls --depth=0 | awk 'NR>1 {print $2}' > dependencies.txt
    
    - name: Generate BE dependencies file and zip
      run: |
        cd ./Code/
        zip -r be.zip BE
        cp -R be.zip ../

        cd BE
        mvn dependency:tree -DoutputType=text | grep -P '^\[INFO\] +- ' | sed 's/^\[INFO\] +- //' > dependencies.txt


    - name: Combine dependencies files and dependency files
      run: |
        mkdir Package
        cp -R be.zip Package
        cp -R fe.zip Package
        zip -r package.zip Package

        touch combined-dependencies.txt
        echo "Angular dependencies:" >> combined-dependencies.txt
        echo " " >> combined-dependencies.txt
        cd ./Code/FE/desofs-news
        cat dependencies.txt >> ../../../combined-dependencies.txt
        cd ../../../Code/BE
        echo "Java dependencies:" >> ../../combined-dependencies.txt
        echo " " >> ../../combined-dependencies.txt
        cat dependencies.txt >> ../../combined-dependencies.txt


    - uses: ncipollo/release-action@v1
      with:
        artifacts: "package.zip"
        bodyFile: "combined-dependencies.txt"
        prerelease: true
        generateReleaseNotes: true